server:
  servlet:
    context-path: /v1

spring:
  application:
    name: CajaViva
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=CajaViva;encrypt=true;trustServerCertificate=true
    username: sa
    password: admin
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
